// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6k5PinNEl2wZkWtcQf9mzxErvNo_vIPM',
    appId: '1:239517033356:android:a5091fb12c69b84c3caca9',
    messagingSenderId: '239517033356',
    projectId: 'brand-shoes-6a471',
    storageBucket: 'brand-shoes-6a471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB87Aj_p3pFyAZnGhTbY_I__eNR-uVBscs',
    appId: '1:239517033356:ios:f2fb3c88292053d63caca9',
    messagingSenderId: '239517033356',
    projectId: 'brand-shoes-6a471',
    storageBucket: 'brand-shoes-6a471.appspot.com',
    iosBundleId: 'com.example.brandShoes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3yl1yIUf2I6MVOVbNyGMES90QGAWwII',
    appId: '1:239517033356:web:8227d3725dc88c603caca9',
    messagingSenderId: '239517033356',
    projectId: 'brand-shoes-6a471',
    authDomain: 'brand-shoes-6a471.firebaseapp.com',
    storageBucket: 'brand-shoes-6a471.appspot.com',
    measurementId: 'G-8YRZ2H5N37',
  );

}